### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by vitalii-kushnirenko** [vitalii-kushnirenko/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by katya-pidpala** [comment]
**–  I am by far the coolest super hero ever to live on this planet. No one was better than me in this matter. I am the most immortal that has ever existed. Wolverine is not as helpful as I am. Thanos - I have love. Sorry losers and haters, but Lady Death is my woman - and you all know it! Please don't fell stupid or insecure, it's not your fault. Since I am a fictional reference to the actor who plays me.**

**Comment by vitalii-kushnirenko** [comment]
Спасибо
