### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by vitalii-kushnirenko** [vitalii-kushnirenko/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by katya-pidpala** [comment]
LANGUAGES 

&#127482ENGLISH  &#127479РУССКИЙ

PERSONALITY
Deadpool is aware that he is a fictional comic book character. He commonly breaks the fourth wall, which is done by few other characters in the Marvel Universe, and this is used to humorous effect. He often has conversations with his two internal monologues, which are shown as caption boxes in his panels; in Deadpool Annual #1 (2014) it is revealed that Madcap, a foe of Captain America, is the psychotic voice appearing in white captions with a typewriter serif; the other voice is unidentified and often mistakenly attributed to Dr. Bong, Deadpool's former psychiatrist.

POWERS AND ABILITIES
Deadpool's primary power is an accelerated healing factor, depicted by various writers at differing levels of efficiency. The speed of his healing factor depends on the severity of the wound and Deadpool's mental state. It works most efficiently when he is awake, alert, and in good spirits. Deadpool's accelerated healing factor is strong enough that he has survived complete incineration and decapitation more than once. Although his head normally has to be reunited with his body to heal a decapitation wound, he was able to regrow his head after having it pulverized by the Hulk in the graphic novel Deadpool Kills the Marvel Universe.

Deadpool is a highly trained assassin and mercenary. He is adept in multiple forms of martial arts, including Savate. Deadpool is an extraordinary athlete, and an expert swordsman and marksman. He is skilled in the use of multiple weapons, including katanas, knives, grenades, and guns. His accelerated healing factor may contribute to his abilities, allowing him to perform intense exercise for extended periods of time with minimal aches and fatigue. Although in earlier years he was originally portrayed as having superhuman strength, he is no longer depicted as having this ability.
 
Over the years, Deadpool has owned a number of personal teleportation devices. Also, during Deadpool's first ongoing comic, he possesses a device which projected holographic disguises, allowing him to go undercover or conceal his appearance. Deadpool is multilingual, with the ability to speak fluently in German, Spanish, ASL, and Japanese, in addition to his native English.

Since Deadpool is aware that he is a fictional character, he uses this knowledge to his advantage to deal with opponents or gain knowledge to which he should not normally have access, such as reading past issues of his and others' comics. For example, Deadpool knows he has a Wikipedia article and hopes his fans keep his page updated.
